# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unlesee you know exactly what you are doing)
enable_modelarts: False
# url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
enable_profiling: False

# ======================================================================================
# Training options
CHARACTER: "0123456789abcdefghijklmnopqrstuvwxyz"

# NUM_CLASS = len(CHARACTER) + 1
NUM_CLASS: 37

HIDDEN_SIZE: 512
FINAL_FEATURE_WIDTH: 26

# dataset config
IMG_H: 32
IMG_W: 100
TRAIN_DATASET_PATH: "CNNCTC_Data/ST_MJ/"
TRAIN_DATASET_INDEX_PATH: "CNNCTC_Data/st_mj_fixed_length_index_list.pkl"
TRAIN_BATCH_SIZE: 192
TRAIN_EPOCHS: 3

# training config
run_distribute: False
PRED_TRAINED: ""
SAVE_PATH: "./"
#LR
base_lr: 0.0005
warmup_step: 2000
warmup_ratio: 0.0625
MOMENTUM: 0.8
LOSS_SCALE: 8096
SAVE_CKPT_PER_N_STEP: 2000
KEEP_CKPT_MAX_NUM: 5

# ======================================================================================
# Eval options
TEST_DATASET_PATH: "CNNCTC_Data/IIIT5k_3000"
TEST_BATCH_SIZE: 256
CHECKPOINT_PATH: ""

# export options
device_id: 0
file_name: "cnnctc"
file_format: "MINDIR"
ckpt_file: ""

# 310 infer
result_path: ""
label_path: ""
preprocess_output: ""

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of input data"
output_pah: "The location of the output file"
device_target: "device id of GPU or Ascend. (Default: None)"
enable_profiling: "Whether enable profiling while training default: False"
file_name: "CNN&CTC output air name"
file_format: "choices [AIR, MINDIR]"
ckpt_file: "CNN&CTC ckpt file"
