# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
need_modelarts_dataset_unzip: True
modelarts_dataset_unzip_name: "coco"

# ==============================================================================
# Train options
data_dir: ""
per_batch_size: 8
pretrained_backbone: ""
resume_yolov4: ""
pretrained_checkpoint: ""
filter_weight: False
lr_scheduler: "cosine_annealing"
lr: 0.012
lr_epochs: "220,250"
lr_gamma: 0.1
eta_min: 0.0
t_max: 320
max_epoch: 320
warmup_epochs: 20
weight_decay: 0.0005
momentum: 0.9
loss_scale: 64
label_smooth: 0
label_smooth_factor: 0.1
log_interval: 100
ckpt_path: "outputs/"
ckpt_interval: -1
is_save_on_master: 1
is_distributed: 1
rank: 0
group_size: 1
need_profiler: 0
training_shape: ""
run_eval: False
save_best_ckpt: True
eval_start_epoch: 200
eval_interval: 1
ann_file: ""

# Eval options
pretrained: ""
log_path: "outputs/"
ann_val_file: ""

# Test option
test_nms_thresh: 0.45
test_ignore_threshold: 0.001

# Export options
device_id: 0
batch_size: 1
testing_shape: 608
ckpt_file: ""
file_name: "yolov4"
file_format: "AIR"
keep_detect: True

# Other default config
hue: 0.1
saturation: 1.5
value: 1.5
jitter: 0.3
resize_rate: 10

multi_scale: [[416, 416],
              [448, 448],
              [480, 480],
              [512, 512],
              [544, 544],
              [576, 576],
              [608, 608],
              [640, 640],
              [672, 672],
              [704, 704],
              [736, 736]
              ]

max_box: 90
backbone_input_shape: [32, 64, 128, 256, 512]
backbone_shape: [64, 128, 256, 512, 1024]
backbone_layers: [1, 2, 8, 8, 4]

ignore_threshold: 0.7
eval_ignore_threshold: 0.001
nms_thresh: 0.5
each_multiscale: True
mosaic: False
multi_label: False
multi_label_thresh: 0.2
detect_head_loss_coff: [1, 1, 1]
bbox_class_loss_coff: [10, 1, 1]
anchor_scales: [[12, 16],
                [19, 36],
                [40, 28],
                [36, 75],
                [76, 55],
                [72, 146],
                [142, 110],
                [192, 243],
                [459, 401]]

num_classes: 80
out_channel: 255 # 3 * (num_classes + 5)
test_img_shape: [608, 608]
labels: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat',
        'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat',
        'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack',
        'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
        'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
        'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
        'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair',
        'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote',
        'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book',
        'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']

checkpoint_filter_list: ['feature_map.backblock0.conv6.weight', 'feature_map.backblock0.conv6.bias',
                         'feature_map.backblock1.conv6.weight', 'feature_map.backblock1.conv6.bias',
                         'feature_map.backblock2.conv6.weight', 'feature_map.backblock2.conv6.bias',
                         'feature_map.backblock3.conv6.weight', 'feature_map.backblock3.conv6.bias']
img_id_file_path: ""
result_files: './result_Files'

---

# Help description for each configuration
# Train options
data_dir: "Train dataset directory."
per_batch_size: "Batch size for Training."
pretrained_backbone: "The ckpt file of CspDarkNet53."
resume_yolov4: "The ckpt file of YOLOv4, which used to fine tune."
pretrained_checkpoint: "The ckpt file of YoloV4CspDarkNet53."
filter_weight: "Filter the last weight parameters"
lr_scheduler: "Learning rate scheduler, options: exponential, cosine_annealing."
lr: "Learning rate."
lr_epochs: "Epoch of changing of lr changing, split with ','."
lr_gamma: "Decrease lr by a factor of exponential lr_scheduler."
eta_min: "Eta_min in cosine_annealing scheduler."
t_max: "T-max in cosine_annealing scheduler."
max_epoch: "Max epoch num to train the model."
warmup_epochs: "Warmup epochs."
weight_decay: "Weight decay factor."
momentum: "Momentum."
loss_scale: "Static loss scale."
label_smooth: "Whether to use label smooth in CE."
label_smooth_factor: "Smooth strength of original one-hot."
log_interval: "Logging interval steps."
ckpt_path: "Checkpoint save location."
ckpt_interval: "Save checkpoint interval."
is_save_on_master: "Save ckpt on master or all rank, 1 for master, 0 for all ranks."
is_distributed: "Distribute train or not, 1 for yes, 0 for no."
rank: "Local rank of distributed."
group_size: "World size of device."
need_profiler: "Whether use profiler. 0 for no, 1 for yes."
training_shape: "Fix training shape."
resize_rate: "Resize rate for multi-scale training."
run_eval: "Run evaluation when training."
save_best_ckpt: "Save best checkpoint when run_eval is True."
eval_start_epoch: "Evaluation start epoch when run_eval is True."
eval_interval: "Evaluation interval when run_eval is True"
ann_file: "path to annotation"
each_multiscale: "Apply multi-scale for each scale"
detect_head_loss_coff: "the loss coefficient of detect head.
                       The order of coefficients is large head, medium head and small head"
bbox_class_loss_coff: "bbox and class loss coefficient.
                       The order of coefficients is ciou loss, confidence loss and class loss"
labels: "the label of train data"
mosaic: "use mosaic data augment"
multi_label: "use multi label to nms"
multi_label_thresh: "multi label thresh"

# Eval options
pretrained: "model_path, local pretrained model to load"
log_path: "checkpoint save location"
ann_val_file: "path to annotation"

# Export options
device_id: "Device id for export"
batch_size: "batch size for export"
testing_shape: "shape for test"
ckpt_file: "Checkpoint file path for export"
file_name: "output file name for export"
file_format: "file format for export"
keep_detect: "keep the detect module or not, default: True"
img_id_file_path: 'path of image dataset'
result_files: 'path to 310 infer result floder'
