# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
checkpoint_file: './checkpoint/mobilenetv1-90_625.ckpt'
device_target: Ascend
enable_profiling: False

# ==============================================================================
modelarts_dataset_unzip_name: 'ImageNet_Original'
need_modelarts_dataset_unzip: True

# config for mobilenet, imagenet2012
class_num: 1001
batch_size: 256
loss_scale: 1024
momentum: 0.9
weight_decay: 0.0001 # 1e-4
epoch_size: 90
pretrain_epoch_size: 0
save_checkpoint: True
save_checkpoint_epochs: 5
keep_checkpoint_max: 10
save_checkpoint_path: "./"
warmup_epochs: 0
lr_decay_mode: "linear"
use_label_smooth: True
label_smooth_factor: 0.1
lr_init: 0
lr_max: 0.8
lr_end: 0.0

# Image classification - train
dataset: 'imagenet2012'
run_distribute: False
device_num: 1
dataset_path: "/cache/data"
pre_trained: ''
parameter_server: False

# Image classification - eval
checkpoint_path: "./mobilenetv1-90_625.ckpt"

# mobilenetv1 export
device_id: 0
ckpt_file: "/cache/data/mobilenetv1-90_625.ckpt"
width: 224
height: 224
file_name: "mobilenetv1"
file_format: "AIR"

# postprocess
result_dir: ''
label_dir: ''
dataset_name: 'imagenet2012'

# preprocess
# data_path: '' help='eval data dir'
result_path: './preprocess_Result/'

---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'
result_dir: "result files path."
label_dir: "image file path."

file_name: "output file name."
dataset: "Dataset, either cifar10 or imagenet2012"
parameter_server: 'Run parameter server train'
width: 'input width'
height: 'input height'
device_target: 'Target device type' 
enable_profiling: 'Whether enable profiling while training, default: False'
only_create_dataset: 'If set it true, only create Mindrecord, default is false.'
run_distribute: 'Run distribute, default is false.'
do_train: 'Do train or not, default is true.'
do_eval: 'Do eval or not, default is false.'
pre_trained: 'Pretrained checkpoint path'
device_id: 'Device id, default is 0.'
device_num: 'Use device nums, default is 1.'
rank_id: 'Rank id, default is 0.'
file_format: 'file format' 
dataset_path: "Change to your own dataset path."
checkpoint_path: "Change to your own ckpt path."

---
device_target: ['Ascend', 'GPU', 'CPU']
file_format: ["AIR", "ONNX", "MINDIR"]
dataset_name: ["cifar10", "imagenet2012"]
