# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
need_modelarts_dataset_unzip: True
modelarts_dataset_unzip_name: "face_recognitionTrack_dataset"

# ==============================================================================
# options
task: 'REID_8p_gpu'

# dataset related
per_batch_size: 16

# network structure related
fp16: 1
loss_scale: 2048.0
input_size: (96, 64)
net_depth: 12
embedding_size: 128

# optimizer related
lr: 0.1
lr_scale: 1
lr_gamma: 1
lr_epochs: '30,60,120,150'
epoch_size: 30
warmup_epochs: 0
steps_per_epoch: 0
max_epoch: 40
weight_decay: 0.0005
momentum: 0.9

# distributed parameter
is_distributed: 1
local_rank: 0
world_size: 8

# logging related
log_interval: 10
ckpt_path: '../output'
ckpt_interval: 200

# train/eval option
data_dir: ''
pretrained: ''
eval_dir: ''

# export option
batch_size: 8
file_name: 'FaceRecognitionForTracking'
file_format: 'AIR'

---
# Help description for each configuration

# train/eval option
data_dir: "image folders"
pretrained: "pretrained model to load"
eval_dir: "eval image dir, e.g. /home/test"

# export option
batch_size: "batch size for export"
file_name: "output file name"
file_format: "file format"