# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
need_modelarts_dataset_unzip: True
modelarts_dataset_unzip_name: "coco"

# ==============================================================================
# Train options
only_create_dataset: False
distribute: False
lr: 0.001
mode: "sink"
epoch_size: 50
batch_size: 32
pre_trained: ""
pre_trained_epoch_size: 0
save_checkpoint_epochs: 5
save_checkpoint_dir: "./"
loss_scale: 1024
mindrecord_dir: "./Mindrecord_train"
image_dir: ""
anno_path: ""

# Eval options
eval_mindrecord_dir: "./Mindrecord_eval"
ckpt_path: ""

# export options
device_id: 0
export_batch_size: 1
ckpt_file: ""
file_name: "yolov3_resnet18"
file_format: "AIR"

---

# Help description for each configuration
# Train options
only_create_dataset: "If set it true, only create Mindrecord."
distribute: "Run distribute"
lr: "Learning rate"
mode: "Run sink mode or not"
epoch_size: "Epoch size"
batch_size: "Batch size"
pre_trained: "Pretrained checkpoint file path"
pre_trained_epoch_size: "Pretrained epoch size"
save_checkpoint_epochs: "Save checkpoint epochs"
loss_scale: "Loss scale"
mindrecord_dir: "Mindrecord directory. If the mindrecord_dir is empty, it wil generate mindrecord file by image_dir and anno_path. Note if mindrecord_dir isn't empty, it will use mindrecord_dir rather than image_dir and anno_path."
image_dir: "Dataset directory, the absolute image path is joined by the image_dir and the relative path in anno_path"
anno_path: "Annotation path."

# Eval options
eval_mindrecord_dir: "Mindrecord directory for eval."
ckpt_path: "Checkpoint path."

# export options
device_id: "Device id"
export_batch_size: "export batch size"
ckpt_file: "Checkpoint file path."
file_name: "output file name."
file_format: "file format. choices in ['AIR', 'ONNX', 'MINDIR']"