# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
need_modelarts_dataset_unzip: False
modelarts_dataset_unzip_name: ""

# ==============================================================================
# options
n_categories: 19
n_sub_categories: 286
n_words: 74308
default_epochs: 1
epochs: -1
lr: 0.001
print_times: 1000
embedding_file: "MINDlarge_utils/embedding_all.npy"
word_dict_path: "MINDlarge_utils/word_dict_all.pkl"
category_dict_path: "MINDlarge_utils/vert_dict.pkl"
subcategory_dict_path: "MINDlarge_utils/subvert_dict.pkl"
uid2index_path: "MINDlarge_utils/uid2index.pkl"
train_dataset_path: "MINDlarge_train"
eval_dataset_path: "MINDlarge_dev"

# default option
seed: 1
platform: "Ascend"
save_graphs: False
dataset: "large"
dataset_path: ""
n_browsed_news: 50
n_words_title: 16
n_words_abstract: 48
word_embedding_dim: 304
category_embedding_dim: 112
query_vector_dim: 208
n_filters: 400
window_size: 3
checkpoint_path: ""
batch_size: 64

# train option
beta1: 0.9
beta2: 0.999
epsilon: 0.00000001 # 1e-8
neg_sample: 4
mixed: True
sink_mode: True
weight_decay: True
save_checkpoint: True
save_checkpoint_path: "./checkpoint"
dropout_ratio: 0.2

# eval option
eval_neg_sample: -1

# export option
export_file_dir: "./"
file_format: "AIR"
export_neg_sample: -1

---

# Help description for each configuration
# default option
seed: "random seed"
platform: "run platform, only support Ascend"
save_graphs: "whether save graphs, default is False."
dataset: "MIND dataset, support large, small and demo."
dataset_path: "MIND dataset path."
n_browsed_news: "number of browsed news per user"
n_words_title: "number of words per title"
n_words_abstract: "number of words per abstract"
word_embedding_dim: "dimension of word embedding vector"
category_embedding_dim: "dimension of category embedding vector"
query_vector_dim: "dimension of the query vector in attention"
n_filters: "number of filters in CNN"
window_size: "size of filter in CNN"
checkpoint_path: "Pre trained checkpoint path, default is None."
batch_size: "size of each batch"

# train option
beta1: "ADAM beta1"
beta2: "ADAM beta2"
epsilon: "ADAM epsilon for numerical stability"
neg_sample: "number of negative samples in negative sampling"
mixed: "whether use mixed precision, default is True."
sink_mode: "whether use dataset sink, default is True."
weight_decay: "whether use weight decay, default is True."
save_checkpoint: "whether save checkpoint, default is True."
save_checkpoint_path: "Save checkpoint path, default is checkpoint."
dropout_ratio: "ratio of dropout"

# export option
file_format: "choices in ['AIR', 'ONNX', 'MINDIR']"