device_target: 'Ascend'                                                 #推理使用服务器的类型,有CPU,GPU,Ascend
device_id: 7                                                            #推理使用的卡的编号


#train
run_distribute: False
is_modelarts: False
no_backbone_params_lr: 0.0001
no_backbone_params_end_lr: 0.0000001
backbone_params_lr: 0.00001
backbone_params_end_lr: 0.00000001
power: 0.5
epoch_size: 400
batch_size: 8
lr_decay: False
train_data_dir: '/midas/'
width_per_group: 8
groups: 32
in_channels: 64
features: 256
layers: [3, 4, 23, 3]
img_width: 384
img_height: 384
nm_img_mean: [0.485, 0.456, 0.406]
nm_img_std: [0.229, 0.224, 0.225]
resize_target: True
keep_aspect_ratio: False
ensure_multiple_of: 32
resize_method: "upper_bound"

#run&export
input_path: '/input'
output_path: '/output'
model_weights: '/ckpt/Midas_0-600_56_1.ckpt'
file_format: "AIR"  #AIR/MIDIR

#eval

datapath_TUM: '/data/TUM'       #TUM数据集地址
datapath_Sintel: '/data/sintel/sintel-data'                                              #Sintel数据集地址
datapath_ETH3D: '/data/ETH3D/ETH3D-data'                                                 #ETH3D数据集地址
datapath_Kitti: '/data/Kitti_raw_data'                                                  #Kitti数据集地址
datapath_DIW: '/data/DIW'                                                                #DIW数据集地址
datapath_NYU: ['/data/NYU/nyu.mat','/data/NYU/splits.mat']       #NYU数据集地址
ann_file: 'val.json'                                                                #存放推理结果的文件地址
ckpt_path: '/midas/ckpt/Midas_0-600_56_1.ckpt'                                                   #存放推理使用的ckpt地址
data_name: 'all'                                                                  #需要推理的数据集名称，有 Sintel,Kitti,TUM,DIW,ETH3D,all
