# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
need_modelarts_dataset_unzip: False
modelarts_dataset_unzip_name: ""

# ==============================================================================
# train options
data_dir: "./data/cora/cora_mr"
train_nodes_num: 140
eval_nodes_num: 500
test_nodes_num: 1000
save_TSNE: False
save_ckptpath: "ckpts/"


---

# Help description for each configuration
data_dir: "Dataset directory"
train_nodes_num: "Nodes numbers for training"
eval_nodes_num: "Nodes numbers for evaluation"
test_nodes_num: "Nodes numbers for test"
save_TSNE: "Whether to save t-SNE graph"