# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
device_target: "Ascend"

# ==============================================================================
# train options
amp_level: "O3"
loss_scale: 1000.0 # for ['O2', 'O3', 'auto']
keep_checkpoint_max: 60
save_epoch_frq: 100
ckpt_save_dir: "./ckpt/"
epoch_size: 6000

# eval options
eval_epoch_frq: 20
self_ensemble: True
save_sr: True

# Adam opt options
opt_type: Adam
weight_decay: 0.0

# learning rate options
learning_rate: 0.0001
milestones: [4000]
gamma: 0.5

# dataset options
dataset_name: "DIV2K"
lr_type: "bicubic"
batch_size: 2
patch_size: 192
scale: 4
dataset_sink_mode: True
need_unzip_in_modelarts: False
need_unzip_files:
 - "DIV2K_train_HR.zip"
 - "DIV2K_train_LR_bicubic_X2.zip"
 - "DIV2K_train_LR_bicubic_X3.zip"
 - "DIV2K_train_LR_bicubic_X4.zip"
 - "DIV2K_train_LR_unknown_X2.zip"
 - "DIV2K_train_LR_unknown_X3.zip"
 - "DIV2K_train_LR_unknown_X4.zip"
 - "DIV2K_valid_HR.zip"
 - "DIV2K_valid_LR_bicubic_X2.zip"
 - "DIV2K_valid_LR_bicubic_X3.zip"
 - "DIV2K_valid_LR_bicubic_X4.zip"
 - "DIV2K_valid_LR_unknown_X2.zip"
 - "DIV2K_valid_LR_unknown_X3.zip"
 - "DIV2K_valid_LR_unknown_X4.zip"

# net options
pre_trained: ""
rgb_range: 255
rgb_mean: [0.4488, 0.4371, 0.4040]
rgb_std: [1.0, 1.0, 1.0]
n_colors: 3
n_feats: 256
kernel_size: 3
n_resblocks: 32
res_scale: 0.1


---
# helper

enable_modelarts: "set True if run in modelarts, default: False"
# Url for modelarts
data_url: "modelarts data path"
train_url: "modelarts code path"
checkpoint_url: "modelarts checkpoint save path"
# Path for local
data_path: "local data path, data will be download from 'data_url', default: /cache/data"
output_path: "local output path, checkpoint will be upload to 'checkpoint_url', default: /cache/train"
device_target: "choice from ['Ascend'], default: Ascend"

# ==============================================================================
# train options
amp_level: "choice from ['O0', 'O2', 'O3', 'auto'], default: O3"
loss_scale: "loss scale will be used except 'O0', default: 1000.0"
keep_checkpoint_max: "max number of checkpoints to be saved,  defalue: 60"
save_epoch_frq: "frequency to save checkpoint, defalue: 100"
ckpt_save_dir: "the relative path to save checkpoint, root path is 'output_path', defalue: ./ckpt/"
epoch_size: "the number of training epochs,  defalue: 6000"

# eval options
eval_epoch_frq: "frequency to evaluate model, defalue: 20"
self_ensemble: "set True if wanna do self-ensemble while evaluating, defalue: True"
save_sr: "set True if wanna save sr and hr image while evaluating, defalue: True"

# opt options
opt_type: "optimizer type, choice from ['Adam'], defalue: Adam"
weight_decay: "weight_decay for optimizer, defalue: 0.0"

# learning rate options
learning_rate: "learning rate, defalue: 0.0001"
milestones: "the key epoch to do a gamma decay, defalue: [4000]" 
gamma: "gamma decay rate, defalue: 0.5" 

# dataset options
dataset_name: "dataset name, defalue: DIV2K"
lr_type: "lr image degeneration type, choice from ['bicubic', 'unknown'], defalue: bicubic"
batch_size: "batch size for training; total batch size = 16 is recommended, defalue: 2"
patch_size: "cut hr images into patch size for training, lr images auto-adjust by 'scale', defalue: 192"
scale: "scale for super resolution reconstruction, choice from [2,3,4], defalue: 4"
dataset_sink_mode: "set True if wanna using dataset sink mode, defalue: True"
need_unzip_in_modelarts: "set True if wanna unzip data after download data from s3, defalue: False"
need_unzip_files: "list of zip files to unzip, only work while 'need_unzip_in_modelarts'=True"

# net options
pre_trained: "load pre-trained model, x2/x3/x4 models can be loaded for each other, choice from [[S3_ABS_PATH], [RELATIVE_PATH below 'output_path'], [LOCAL_ABS_PATH], ''], defalue: ''"
rgb_range: "pix value range, defalue: 255"
rgb_mean: "rgb mean, defalue: [0.4488, 0.4371, 0.4040]"
rgb_std: "rgb standard deviation, defalue: [1.0, 1.0, 1.0]"
n_colors: "the number of RGB image channels, defalue: 3"
n_feats: "the number of output features for each Conv2d, defalue: 256"
kernel_size: "kernel size for Conv2d, defalue: 3"
n_resblocks: "the number of resblocks, defalue: 32"
res_scale: "zoom scale of res branch, defalue: 0.1"
