# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
checkpoint_path: './checkpoint/'
device_target: GPU
enable_profiling: False

# ==============================================================================
modelarts_dataset_unzip_name: 'ImageNet_Original'
need_modelarts_dataset_unzip: True

num_classes: 1000
image_height: 224
image_width: 224
num_workers: 8
boost_mode: "O0"
batch_size: 150
epoch_size: 200
warmup_epochs: 0
lr_init: .0
lr_end: .0
lr_max: 0.8
momentum: 0.9
weight_decay: 0.00004 # 4e-5
label_smooth: 0.1
loss_scale: 1024
save_checkpoint: True
save_checkpoint_epochs: 1
keep_checkpoint_max: 200
save_checkpoint_path: "./"
platform: 'GPU'
device_id: 0
rank_id: 0
rank_size: 1
run_distribute: True
activation: "Softmax"

# Image classification trian. train_parse_args():return train_args
dataset_path: "/cache/data"
pretrain_ckpt: "./mobilenetv2-200_625.ckpt"
freeze_layer: ""
filter_head: False
enable_cache: False
cache_session_id: ""
is_training: True

# mobilenetv2 eval
is_training_eval: False
run_distribute_eval: False

# mobilenetv2 export
device_id_export: 0
batch_size_export: 1
ckpt_file: "/cache/train/mobilenetv2-200_625.ckpt"
file_name: "mobilenetv2"
file_format: "MINDIR"
is_training_export: False
run_eval: False
run_distribute_export: False

# postprocess.py / mobilenetv2 acc calculation
batch_size_postprocess: 1
result_path: ''
label_path: ''

---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'
ann_file: 'Ann file, default is val.json.'

pretrain_ckpt: 'Pretrained checkpoint path for fine tune or incremental learning'
platform: 'Target device type'
freeze_layer: 'freeze the weights of network from start to which layers'
filter_head: 'Filter head weight parameters when load checkpoint, default is False.'
enable_cache: 'Caching the dataset in memory to speedup dataset processing, default is False.'
cache_session_id: 'The session id for cache service.'
file_name: "output file name."
result_path: "result files path."
label_path: "label path."
enable_profiling: 'Whether enable profiling while training, default: False'
run_eval: 'Whether run evaluation while training, default is false.'
run_distribute: 'Run distribute, default is false.'
device_id: 'Device id, default is 0.'
rank_id: 'Rank id, default is 0.'
file_format: 'file format'

---
platform: ['Ascend', 'GPU', 'CPU']
file_format: ["AIR", "ONNX", "MINDIR"]
freeze_layer: ["", "none", "backbone"]
