# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
checkpoint_path: './checkpoint/'
checkpoint_file: './checkpoint/checkpoint_alexnet-30_1562.ckpt'
device_target: Ascend
enable_profiling: False

ckpt_path: "/cache/data"
ckpt_file: "/cache/data/checkpoint_alexnet-30_1562.ckpt"
# ==============================================================================
# Training options
num_classes: 1000
learning_rate: 0.13
momentum: 0.9
epoch_size: 150
batch_size: 256
buffer_size: None
image_height: 224
image_width: 224
save_checkpoint_steps: 625
keep_checkpoint_max: 10
air_name: 'alexnet.air'

weight_decay: 0.0001
loss_scale: 1024
is_dynamic_loss_scale: 0

# Model Description
model_name: alexnet
file_name: 'alexnet'
file_format: 'AIR'

dataset_name: 'imagenet'
sink_size: -1
dataset_sink_mode: True
device_id: 0
save_checkpoint: True
save_checkpoint_epochs: 2
lr: 0.01


---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

device_target: 'Target device type' 
enable_profiling: 'Whether enable profiling while training, default: False'

---
device_target: ['Ascend', 'GPU', 'CPU']