# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
checkpoint_path: './checkpoint/'
checkpoint_file: './checkpoint/checkpoint_alexnet-30_1562.ckpt'
device_target: Ascend
enable_profiling: False

ckpt_path: "/cache/train"
ckpt_file: "/cache/train/checkpoint_alexnet-30_1562.ckpt"
# ==============================================================================
# Training options
epoch_size: 30
keep_checkpoint_max: 10
num_classes: 10
learning_rate: 0.002
momentum: 0.9
batch_size: 32
buffer_size: 1000
image_height: 227
image_width: 227
save_checkpoint_steps: 1562
air_name: 'alexnet.air'

dataset_name: 'cifar10'
sink_size: -1
dataset_sink_mode: True
device_id: 0
save_checkpoint: True
save_checkpoint_epochs: 2
lr: 0.01

# Model Description
model_name: alexnet
file_name: 'alexnet'
file_format: 'AIR'


---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

device_target: 'Target device type' 
enable_profiling: 'Whether enable profiling while training, default: False'

---
device_target: ['Ascend', 'GPU', 'CPU']