# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unlesee you know exactly what you are doing)
enable_modelarts: False
# url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
enable_profiling: False
modelarts_home: "/home/work/user-job-dir"
object_name: "ctpn"

# ======================================================================================
# common options
run_distribute: False

# ======================================================================================
# Training options
img_width: 960
img_height: 576
keep_ratio: False
flip_ratio: 0.0
photo_ratio: 0.0
expand_ratio: 1.0

# anchor
num_anchors: 14
anchor_base: 16
anchor_height: [2, 4, 7, 11, 16, 23, 33, 48, 68, 97, 139, 198, 283, 406]
anchor_width: [16]

# rpn
rpn_in_channels: 256
rpn_feat_channels: 512
rpn_loss_cls_weight: 1.0
rpn_loss_reg_weight: 3.0
rpn_cls_out_channels: 2

# bbox_assign_sampler
neg_iou_thr: 0.5
pos_iou_thr: 0.7
min_pos_iou: 0.001
num_gts: 256
num_expected_neg: 512
num_expected_pos: 256

# proposal
activate_num_classes: 2
use_sigmoid_cls: False

# train proposal
rpn_proposal_nms_across_levels: False
rpn_proposal_nms_pre: 2000
rpn_proposal_nms_post: 1000
rpn_proposal_max_num: 1000
rpn_proposal_nms_thr: 0.7
rpn_proposal_min_bbox_size: 8

# rnn structure
input_size: 512
hidden_size: 128

# training
warmup_mode: "linear"
# batch_size only support 1
batch_size: 1
momentum: 0.9
save_checkpoint: True
save_checkpoint_epochs: 10
keep_checkpoint_max: 5
save_checkpoint_path: "./"
use_dropout: False
loss_scale: 1
weight_decay: 1e-4
pre_trained: ""
task_type: "Pretraining"
run_eval: False
save_best_ckpt: True
eval_image_path: ""
eval_dataset_path: ""
eval_start_epoch: 10
eval_interval: 10

# text proposal connection
max_horizontal_gap: 60
text_proposals_min_scores: 0.7
text_proposals_nms_thresh: 0.2
min_v_overlaps: 0.7
min_size_sim: 0.7
min_ratio: 0.5
line_min_score: 0.9
text_proposals_width: 16
min_num_proposals: 2

# create dataset
coco_root: ""
coco_train_data_type: ""
cocotext_json: ""
icdar11_train_path: []
icdar13_train_path: []
icdar15_train_path: []
icdar13_test_path: []
flick_train_path: []
svt_train_path: []
pretrain_dataset_path: ""
finetune_dataset_path: ""
test_dataset_path: ""

# training dataset
pretraining_dataset_file: ""
finetune_dataset_file: ""

# pretrain lr
pre_base_lr: 0.009
pre_warmup_step: 30000
pre_warmup_ratio: 1/3
pre_total_epoch: 100

# finetune lr
fine_base_lr: 0.005
fine_warmup_step: 300
fine_warmup_ratio: 1/3
fine_total_epoch: 50

# ======================================================================================
# Eval options
rpn_nms_pre: 2000
rpn_nms_post: 1000
rpn_max_num: 1000
rpn_nms_thr: 0.7
rpn_min_bbox_min_size: 8
test_iou_thr: 0.7
test_max_per_img: 1000
test_batch_size: 1
use_python_proposal: False
dataset_path: ""
image_path: ""
checkpoint_path: ""
img_dir: ""

# ======================================================================================
# export options
device_id: 0
file_name: "cnnctc"
file_format: "MINDIR"
ckpt_file: ""

# ======================================================================================
# postprocess
export_dataset_path: ""
result_path: ""
label_path: ""

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of input data"
output_pah: "The location of the output file"
device_target: "device id of GPU or Ascend. (Default: None)"
enable_profiling: "Whether enable profiling while training default: False"
file_name: "CNN&CTC output air name"
file_format: "choices [AIR, MINDIR]"
ckpt_file: "CNN&CTC ckpt file"
run_distribute: "Run distribute, default: false."
pre_trained: "Pretrained file path."
device_id: "Device id, default: 0."
task_type: "Pretraining choices [Pretraining, Finetune]"
run_eval: "Run evaluation when training, default is False."
save_best_ckpt: "Save best checkpoint when run_eval is True, default is True."
eval_image_path: "eval image path, when run_eval is True, eval_image_path should be set."
eval_dataset_path: "eval dataset path, when run_eval is True, eval_dataset_path should be set."
eval_start_epoch: "Evaluation start epoch when run_eval is True, default is 10."
eval_interval: "Evaluation interval when run_eval is True, default is 10."
dataset_path: "Dataset path."
image_path: "Image path."
checkpoint_path: "Checkpoint file path."
