AddExt: 'aclnnAdd'
Bmm: 'aclnnBatchMatMul'
Concat: 'aclnnCat'
SiLU: 'aclnnSilu'
Pow: 'aclnnPowTensorTensor'
MatMul: 'aclnnMatmul'
MaskedFill: 'aclnnInplaceMaskedFillTensor'
GreaterEqual: 'aclnnGeTensor'
GeLU: 'aclnnGelu'
GeLUGrad: 'aclnnGeluBackward'
Less: 'aclnnLtTensor'
SubExt: 'aclnnSub'
Sum: 'aclnnReduceSum'
SigmoidGrad: 'aclnnSigmoidBackward'
SiLUGrad: 'aclnnSiluBackward'
GatherDGradV2: 'aclnnScatterAdd'
GatherD: 'aclnnGather'
ReLU: 'aclnnRelu'
ReLUGrad: 'aclnnThresholdBackward'
Tile: 'aclnnRepeat'
Transpose: 'aclnnPermute'
Equal: 'aclnnEqTensor'
Greater: 'aclnnGtTensor'
ArgMaxWithValue: 'aclnnMaxDim'
ArgMinWithValue: 'aclnnMinDim'
