Bmm: 'aclnnBatchMatMul'
SiLU: 'aclnnSilu'
Pow: 'aclnnPowTensorTensor'
MatMul: 'aclnnMatmul'
MaskedFill: 'aclnnInplaceMaskedFillTensor'
GreaterEqual: 'aclnnGeTensor'
Less: 'aclnnLtTensor'
Sum: 'aclnnReduceSum'
SigmoidGrad: 'aclnnSigmoidBackward'
SiLUGrad: 'aclnnSiluBackward'