AddExt: 'aclnnAdd'
Bmm: 'aclnnBatchMatMul'
BatchMatMulExt: 'aclnnBatchMatMul'
Concat: 'aclnnCat'
SiLU: 'aclnnSilu'
Pow: 'aclnnPowTensorTensor'
Embedding: 'aclnnEmbedding'
EmbeddingDenseGrad: 'aclnnEmbeddingDenseGrad'
MatMulExt: 'aclnnMatmul'
MaskedFill: 'aclnnInplaceMaskedFillTensor'
GreaterEqual: 'aclnnGeTensor'
UniformExt: 'aclnnInplaceUniform'
GeLU: 'aclnnGelu'
GeLUGrad: 'aclnnGeluBackward'
ReverseV2: 'aclnnFlip'
Less: 'aclnnLtTensor'
LessEqual: 'aclnnLeTensor'
SubExt: 'aclnnSub'
Sum: 'aclnnReduceSum'
SigmoidGrad: 'aclnnSigmoidBackward'
SiLUGrad: 'aclnnSiluBackward'
GatherDGradV2: 'aclnnScatterAdd'
GatherD: 'aclnnGather'
ReLU: 'aclnnRelu'
ReLUGrad: 'aclnnThresholdBackward'
LinSpaceExt: 'aclnnLinspace'
Tile: 'aclnnRepeat'
Transpose: 'aclnnPermute'
ArgMaxExt: 'aclnnArgMax'
Equal: 'aclnnEqTensor'
Greater: 'aclnnGtTensor'
ArgMaxWithValue: 'aclnnMaxDim'
ArgMinWithValue: 'aclnnMinDim'
ConstantPadND: 'aclnnConstantPadNd'
ReflectionPad1D: 'aclnnReflectionPad1d'
ReflectionPad2D: 'aclnnReflectionPad2d'
ReflectionPad3D: 'aclnnReflectionPad3d'
ReflectionPad1DGrad: 'aclnnReflectionPad1dBackward'
ReflectionPad2DGrad: 'aclnnReflectionPad2dBackward'
ReflectionPad3DGrad: 'aclnnReflectionPad3dBackward'
ReplicationPad1D: 'aclnnReplicationPad1d'
ReplicationPad2D: 'aclnnReplicationPad2d'
ReplicationPad3D: 'aclnnReplicationPad3d'
ReplicationPad1DGrad: 'aclnnReplicationPad1dBackward'
ReplicationPad2DGrad: 'aclnnReplicationPad2dBackward'
ReplicationPad3DGrad: 'aclnnReplicationPad3dBackward'
ReduceAny: 'aclnnAny'
NormalExt: 'aclnnNormalTensorTensor'
GroupNormGrad: 'aclnnGroupNormBackward'
NotEqual: 'aclnnNeTensor'
ClampScalar: 'aclnnClamp'
OneHotExt: 'aclnnOneHot'
Select: 'aclnnSWhere'
MaxPoolWithIndices: 'aclnnMaxPool2dWithIndices'
MaxpoolGradWithIndices: 'aclnnMaxPool2dWithIndicesBackward'
MaxPoolWithMask: 'aclnnMaxPool2dWithMask'
MaxPoolGradWithMask: 'aclnnMaxPool2dWithMaskBackward'
