Bmm: 'aclnnBatchMatMul'
Concat: 'aclnnCat'
SiLU: 'aclnnSilu'
Pow: 'aclnnPowTensorTensor'
MatMul: 'aclnnMatmul'
MaskedFill: 'aclnnInplaceMaskedFillTensor'
GreaterEqual: 'aclnnGeTensor'
Less: 'aclnnLtTensor'
Sum: 'aclnnReduceSum'
SigmoidGrad: 'aclnnSigmoidBackward'
SiLUGrad: 'aclnnSiluBackward'
Tile: 'aclnnRepeat'
GatherExt: 'aclnnGather'
Equal: 'aclnnEqTensor'
Greater: 'aclnnGtTensor'