# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unlesee you know exactly what you are doing)
enable_modelarts: False
# url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
enable_profiling: False

# ======================================================================================
# create ignore mask options
train_dir: ""
val_dir: ""
train_ann: ""
val_ann: ""
vis: False

# ======================================================================================
# Training options
imgpath_train: ""
jsonpath_train: ""
maskpath_train: ""
save_model_path: "./checkpoint/"
load_pretrain: False
pretrained_model_path: ""

# train type
train_type: "fix_loss_scale"
train_type_NP: "clip_grad"

# vgg bn
vgg_with_bn: False
vgg_path: ""

#if clip_grad
GRADIENT_CLIP_TYPE: 1
GRADIENT_CLIP_VALUE: 10.0

# optimizer and lr
optimizer: "Adam"
optimizer_NP: "Momentum"
group_params: True
group_params_NP: False
lr: 1e-4
lr_type: "default"   # chose in [default, cosine]
lr_gamma: 0.1
lr_steps: "100000,200000,250000"
lr_steps_NP: "250000,300000"
warmup_epoch: 5
max_epoch_train: 60
max_epoch_train_NP: 80
loss_scale: 16384

# default param
batch_size: 10
min_keypoints: 5
min_area: 1024
insize: 368
downscale: 8
paf_sigma: 8
heatmap_sigma: 7
keep_checkpoint_max: 5
log_interval: 100
ckpt_interval: 5304
min_box_size: 64
max_box_size: 512
min_scale: 0.5
max_scale: 2.0
max_rotate_degree: 40
center_perterb_max: 40

# ======================================================================================
# Eval options
is_distributed: 0
eva_num: 100
model_path: ""
imgpath_val: ""
ann: ""
output_img_path: "./output_imgs/"

# inference params
inference_img_size: 368
inference_scales: [0.5, 1, 1.5, 2]
heatmap_size: 320
gaussian_sigma: 2.5
ksize: 17
n_integ_points: 10
n_integ_points_thresh: 8
heatmap_peak_thresh: 0.05
inner_product_thresh: 0.05
limb_length_ratio: 1.0
length_penalty_value: 1
n_subset_limbs_thresh: 3
subset_score_thresh: 0.2

# face params
face_inference_img_size: 368
face_heatmap_peak_thresh: 0.1
face_crop_scale: 1.5
face_line_indices: [
        [0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10], [10, 11], [11, 12], [12, 13], [13, 14], [14, 15], [15, 16], # 轮廓
        [17, 18], [18, 19], [19, 20], [20, 21],
        [22, 23], [23, 24], [24, 25], [25, 26],
        [27, 28], [28, 29], [29, 30],
        [31, 32], [32, 33], [33, 34], [34, 35],
        [36, 37], [37, 38], [38, 39], [39, 40], [40, 41], [41, 36],
        [42, 43], [43, 44], [44, 45], [45, 46], [46, 47], [47, 42],
        [48, 49], [49, 50], [50, 51], [51, 52], [52, 53], [53, 54], [54, 55], [55, 56], [56, 57], [57, 58], [58, 59], [59, 48], # 唇外廓
        [60, 61], [61, 62], [62, 63], [63, 64], [64, 65], [65, 66], [66, 67], [67, 60]
]

# hand params
hand_inference_img_size: 368
hand_heatmap_peak_thresh: 0.1
fingers_indices: [
        [[0, 1], [1, 2], [2, 3], [3, 4]],
        [[0, 5], [5, 6], [6, 7], [7, 8]],
        [[0, 9], [9, 10], [10, 11], [11, 12]],
        [[0, 13], [13, 14], [14, 15], [15, 16]],
        [[0, 17], [17, 18], [18, 19], [19, 20]],
]

# ======================================================================================
#export options
device_id: 0
export_batch_size: 1
ckpt_file: ""
file_name: "openpose"
file_format: "MINDIR"

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of input data"
output_pah: "The location of the output file"
device_target: "device id of GPU or Ascend. (Default: None)"
enable_profiling: "Whether enable profiling while training default: False"
is_distributed: "Run distribute, default is false."
device_id: "device id"
export_batch_size: "batch size"
file_name: "output file name"
file_format: "file format choices[AIR, MINDIR, ONNX]"
ckpt_file: "Checkpoint file path."
model_path: "path of testing model"
imgpath_val: "path of testing imgs"
ann: "path of annotations"
output_img_path: "path of testing imgs"
vis: "visualize annotations and ignore masks"
val_ann: "val annotations json"
train_ann: "train annotations json"
train_dir: "name of train dir"
val_dir: "name of val dir"
