# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: Ascend
enable_profiling: False

ckpt_path: '/cache/data/'
ckpt_file: '/cache/data/checkpoint_lenet-10_1875.ckpt'

# ==============================================================================
# Training options
num_classes: 10
lr: 0.01
momentum: 0.9
epoch_size: 10
batch_size: 15 # 32
buffer_size: 1000
image_height: 32
image_width: 32
save_checkpoint_steps: 1875
keep_checkpoint_max: 10
air_name: "lenet"
device_id: 0
file_name: "lenet"
file_format: "AIR"

model_name: lenet
learning_rate: 0.002
dataset_name: 'mnist'
sink_size: -1
dataset_sink_mode: True
save_checkpoint: True
save_checkpoint_epochs: 2

---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

device_target: 'Target device type' 
enable_profiling: 'Whether enable profiling while training, default: False'
file_name: 'output file name.'
file_format: 'file format'

---
device_target: ['Ascend', 'GPU', 'CPU']
file_format: ['AIR', 'ONNX', 'MINDIR']
