# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
need_modelarts_dataset_unzip: True
modelarts_dataset_unzip_name: "amazon_beauty"

# ==============================================================================
# options
dataset: "Beauty"
datapath: "./scripts/data_mr"
Ks: [5, 10, 20, 100]
workers: 8
ckptpath: "../ckpts"
epsilon: 0.00000001 # 1e-8
learning_rate: 0.001 # 1e-3
l2: 0.03
activation: "tanh"
neighbor_dropout: [0.0, 0.2, 0.3]
log_name: "test"
num_epoch: 600
input_dim: 64
batch_pairs: 5000
eval_interval: 20
num_neg: 10
raw_neighs: 40
gnew_neighs: 20
embedded_dimension: 64
dist_reg: 0.003

# export option
device_id: 0
ckpt_file: ""
file_name: "bgcf"
file_format: "AIR"
row_neighs: 40

---

# Help description for each configuration
dataset: "choose which dataset"
datapath: "minddata path"
Ks: "top K"
workers: "number of process to generate data"
ckptpath: "checkpoint path"
epsilon: "optimizer parameter"
learning_rate: "learning rate"
l2: "l2 coefficient"
activation: "activation function, choices in ['relu', 'tanh']."
neighbor_dropout: "dropout ratio for different aggregation layer"
log_name: "log name"
num_epoch: "epoch sizes for training"
input_dim: "user and item embedding dimension, choices in [64, 128]"
batch_pairs: "batch size"
eval_interval: "evaluation interval"
num_neg: "negative sampling rate "
raw_neighs: "num of sampling neighbors in raw graph"
gnew_neighs: "num of sampling neighbors in sample graph"
embedded_dimension: "output embedding dim"
dist_reg: "distance loss coefficient"
device_target: "device target, choices in ['Ascend', GPU]"

# export option
device_id: "Device id"
ckpt_file: "Checkpoint file path."
file_name: "output file name."
file_format: "file format, choices in ['AIR', 'ONNX', 'MINDIR']"
row_neighs: "num of sampling neighbors in raw graph"