# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
checkpoint_path: './checkpoint/'
checkpoint_file: './checkpoint/lstm-20_390.ckpt'
device_target: CPU
enable_profiling: False

# ==============================================================================
# LSTM CONFIG
num_classes: 2
dynamic_lr: False
learning_rate: 0.1
momentum: 0.9
num_epochs: 20
batch_size: 64
embed_size: 300
num_hiddens: 100
num_layers: 2
bidirectional: True
save_checkpoint_steps: 390
keep_checkpoint_max: 10

# MindSpore LSTM Example - train.py
preprocess: 'false'
aclimdb_path: "./aclImdb"
glove_path: "/cache/data"
preprocess_path: "/cache/train/preprocess"
ckpt_path: './ckpt_lstm/'
pre_trained: '' # None
device_num: 1
distribute: "false"
enable_graph_kernel: "true"

# export.py
ckpt_file: './ckpt_lstm/lstm-20_390.ckpt'
device_id: 0
file_name: "lstm"
file_format: "AIR"

# LSTM Postprocess
label_dir: ''
result_dir: "./result_Files"

# preprocess
result_path: './preprocess_Result/'

---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

preprocess: 'whether to preprocess data.'
aclimdb_path: 'path where the dataset is stored.'
glove_path: 'path where the GloVe is stored.'
preprocess_path: 'path where the pre-process data is stored.'
ckpt_path: 'the path to save the checkpoint file.'
pre_trained: 'the pretrained checkpoint file path.'
device_target: 'the target device to run, support "GPU", "CPU". Default: "Ascend".'
device_num: 'Use device nums, default is 1.'
distribute: 'Run distribute, default is false.'
enable_graph_kernel: 'Accelerate by graph kernel, default is true.'

---
device_target: ['Ascend', 'GPU', 'CPU']
distribute: ['true', 'false']
enable_graph_kernel: ['true', 'false']
file_format: ['AIR', 'MINDIR']
