# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unlesee you know exactly what you are doing)
enable_modelarts: False
# url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
enable_profiling: False

# ======================================================================================
# common options
is_distributed: 0
image_size: [224, 224]
batch_size: 32
num_parallel_workers: 4
rank: 0
group_size: 1
num_classes: 1000
label_smooth: False
label_smooth_factor: 0.0

# ======================================================================================
# Training options
backbone: 'dpn92'
is_save_on_master: True

# training config
pretrained: ""
ckpt_path: "./"
eval_each_epoch: 0
global_step: 0
epoch_size: 180
loss_scale_num: 1024
momentum: 0.9
weight_decay: 1e-4

# learning rate config
lr_schedule: "warmup"
lr_init: 0.01
lr_max: 0.1
factor: 0.1
epoch_number_to_drop: [5, 15]
warmup_epochs: 5

# dataset config
train_data_dir: ""
dataset: "imagenet-1K"
keep_checkpoint_max: 3

# ======================================================================================
# Eval options
eval_data_dir: ""
checkpoint_path: ""


# export options
device_id: 0
width: 224
height: 224
file_name: "dpn"
file_format: "MINDIR"


---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of input data"
output_pah: "The location of the output file"
device_target: "device id of GPU or Ascend. (Default: None)"
enable_profiling: "Whether enable profiling while training default: False"
train_data_dir: "Imagenet train data dir"
pretrained: "ckpt path to load"
is_distributed: "if multi device"
ckpt_path: "ckpt path to save"
eval_each_epoch: "evaluate on each epoch"
eval_data_dir: "eval data dir"
checkpoint_path: "ckpt path to load"
device_id: "device id"
width: "input width"
height: "input height"
file_name: "dpn output file name"
file_format: "choices [AIR, ONNX, MINDIR]"
