# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unlesee you know exactly what you are doing)
enable_modelarts: False
# url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
enable_profiling: False

# ======================================================================================
# common options
run_distribute: False
model: "lowercase"
model_version: "V1"

# ======================================================================================
# Training options
label_dict: "abcdefghijklmnopqrstuvwxyz0123456789"
train_dataset: "synth"
max_text_length: 23
image_width: 100
image_height: 32
batch_size: 64
epoch_size: 10
hidden_size: 256
learning_rate: 0.02
momentum: 0.95
nesterov: True
save_checkpoint: True
save_checkpoint_steps: 1000
keep_checkpoint_max: 30
per_print_time: 100
save_checkpoint_path: "./"
class_num: 37
input_size: 512
num_step: 24
use_dropout: True
blank: 36
train_dataset_path: ""
train_eval_dataset: "svt"
train_eval_dataset_path: ""
run_eval: False
eval_all_saved_ckpts: False
save_best_ckpt: True
eval_start_epoch: 5
eval_interval: 1

# ======================================================================================
# Eval options
eval_dataset: "svt"
eval_dataset_path: ""
checkpoint_path: ""

# ======================================================================================
# export options
device_id: 0
ckpt_file: ""
file_name: "crnn"
file_format: "MINDIR"

# ======================================================================================
#postprocess
ann_file: ""
result_path: ""
dataset: "ic03"

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of input data"
output_pah: "The location of the output file"
device_target: "device id of GPU or Ascend. (Default: None)"
enable_profiling: "Whether enable profiling while training default: False"
file_name: "CNN&CTC output air name"
file_format: "choices [AIR, MINDIR]"
ckpt_file: "Checkpoint file path."
run_distribute: "Run distribute, default is false."
train_dataset_path: "train Dataset path, default is None"
model: "Model type, default is lowercase"
train_dataset: "choices [synth, ic03, ic13, svt, iiit5k]"
train_eval_dataset: "choices [synth, ic03, ic13, svt, iiit5k]"
train_eval_dataset_path: "Dataset path, default is None"
run_eval: "Run evaluation when training, default is False."
save_best_ckpt: "Save best checkpoint when run_eval is True, default is True."
eval_start_epoch: "Evaluation start epoch when run_eval is True, default is 5."
eval_interval: "Evaluation interval when run_eval is True, default is 5."
eval_dataset_path: "eval Dataset, default is None."
checkpoint_path: "checkpoint file path, default is None"
ann_file: "ann file."
result_path: "image file path."
dataset: "choices=['ic03', 'ic13', 'svt', 'iiit5k']"
