# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: Ascend
enable_profiling: False

# ==============================================================================
dataset_path: "/cache/data"
ckpt_path: '/cache/data/'
checkpoint_path: './inceptionv4/inceptionv4-train-250_1251.ckpt'
ckpt_file: '/cache/data/ImageNet_Original/inceptionv4/inceptionv4-train-250_1251.ckpt'
resume: ''
is_distributed: False
device_id: 0
platform: 'Ascend'
file_name: 'inceptionv4'
file_format: 'MINDIR'
width: 299
height: 299

modelarts_dataset_unzip_name: 'ImageNet_Original'
need_modelarts_dataset_unzip: True
ckpt_save_dir: './ckpt/'

# postprocess.py fasterrcnn_export
result_path: ''
label_file: ''

# Training options
is_save_on_master: False

batch_size: 128
epoch_size: 250
num_classes: 1000
work_nums: 8
ds_type: 'imagenet'
ds_sink_mode: True

loss_scale: 1024
smooth_factor: 0.1
weight_decay: 0.00004
momentum: 0.9
amp_level: 'O3'
decay: 0.9
epsilon: 1.0

keep_checkpoint_max: 10
save_checkpoint_epochs: 10

lr_init: 0.00004
lr_end: 0.000004
lr_max: 0.4
warmup_epochs: 1
start_epoch: 1
    

---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

device_target: 'Target device type' 
enable_profiling: 'Whether enable profiling while training, default: False'
file_name: 'output file name.'
file_format: 'file format'
resume: 'resume training with existed checkpoint'
result_path: "result file path"
label_file: "label file"

---
device_target: ['Ascend', 'GPU', 'CPU']
file_format: ['AIR', 'ONNX', 'MINDIR']
