# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unlesee you know exactly what you are doing)
enable_modelarts: False
# url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
enable_profiling: False
checkpoint_path: "./checkpoint/"
checkpoint_file: "./checkpoint/.ckpt"
modelarts_home: "/home/work/user-job-dir"
object_name: "psenet"

# ======================================================================================
# Training options
pre_trained: ""
INFER_LONG_SIZE: 1920
KERNEL_NUM: 7
run_distribute: False

# backbone
BACKBONE_LAYER_NUMS: [3, 4, 6, 3]
BACKBONE_IN_CHANNELS: [64, 256, 512, 1024]
BACKBONE_OUT_CHANNELS: [256, 512, 1024, 2048]

# neck
NECK_OUT_CHANNEL: 256

# lr
BASE_LR: 2e-3
TRAIN_TOTAL_ITER: 58000
WARMUP_STEP: 620
WARMUP_RATIO: 1/3

# dataset for train
TRAIN_ROOT_DIR: ""
TRAIN_LONG_SIZE: 640
TRAIN_MIN_SCALE: 0.4
TRAIN_BATCH_SIZE: 4
TRAIN_REPEAT_NUM: 1800
TRAIN_DROP_REMAINDER: True
TRAIN_MODEL_SAVE_PATH: "./"

# ======================================================================================
# Eval options
ckpt: ""
TEST_ROOT_DIR: ""
TEST_BUFFER_SIZE: 4
TEST_DROP_REMAINDER: False
INFERENCE: True

# ======================================================================================
#export options
device_id: 0
batch_size: 1
file_name: "psenet"
file_format: "MINDIR"

# ======================================================================================
#postprocess
result_path: "./scripts/result_Files"
img_path: ""

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of input data"
output_pah: "The location of the output file"
device_target: "device id of GPU or Ascend. (Default: None)"
enable_profiling: "Whether enable profiling while training default: False"
run_distribute: "Run distribute, default is false."
pre_trained: "Pretrain file path"
ckpt: "trained model path"
device_id: "device id"
batch_size: "batch size"
file_name: "output file name"
file_format: "file format choices[AIR, MINDIR, ONNX]"
object_home: "your direction name"
modelarts_home: "modelarts working path"
result_path: "result Files path."
img_path: "image files path."
