# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
need_modelarts_dataset_unzip: False
modelarts_dataset_unzip_name: ""

# ==============================================================================
# options
vocab_size: 6596536
buckets: [64, 128, 256, 512, 3013]
test_buckets: [64, 128, 256, 512, 1120]
batch_size: 4096
embedding_dims: 16
num_class: 14
epoch: 5
lr: 0.8
min_lr: 0.000001 # 1e-6
decay_steps: 549
warmup_steps: 400000
poly_lr_scheduler_power: 0.5
epoch_count: 1
pretrain_ckpt_dir: ""
save_ckpt_steps: 548
save_ckpt_dir: "./"
keep_ckpt_max: 10
distribute_batch_size_gpu: 512

dataset_path: ""
data_name: "dbpedia"
run_distribute: False
model_ckpt: ""
# export option
device_id: 0
ckpt_file: ""
file_name: "fasttexts"
file_format: "AIR"
---

# Help description for each configuration
device_target: "Device target"
dataset_path: "FastText input data file path."
data_name: "dataset name. choice in ['ag', 'dbpedia', 'yelp_p']"
run_distribute: "Run distribute, default: false."
model_ckpt: "existed checkpoint address."
# export option
device_id: "Device id"
ckpt_file: "Checkpoint file path"
file_name: "Output file name"
file_format: "Output file format, choice in ['AIR', 'ONNX', 'MINDIR']"